version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
      - db=mysql
      - jdbc_url=jdbc:mysql://mysql:3306/conductor
      - conductor_mysql_connection_pool_size_max=10
      - conductor_mysql_connection_pool_idle_min=2
      - workflow_elasticsearch_url=http://es:9200
      - workflow_elasticsearch_cluster_health_color=yellow
    image: conductor:server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    links:
      - elasticsearch:es
      - mysql:mysql
    healthcheck:
      test: timeout -t 5 sh -c 'nc -z localhost 8080'
      interval: 5s
      timeout: 5s
      retries: 12
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_healthy

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor:ui
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server
    healthcheck:
      test: timeout -t 5 sh -c 'nc -z localhost 5000'
      interval: 5s
      timeout: 5s
      retries: 12
    depends_on:
      conductor-server:
        condition: service_healthy

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: conductor
      MYSQL_USER: conductor
      MYSQL_PASSWORD: password
    volumes:
      - type: volume
        source: conductor_mysql
        target: /var/lib/mysql
    networks:
      - internal
    ports:
      - 3306:3306
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/3306'
      interval: 5s
      timeout: 5s
      retries: 12

  # https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9200'
      interval: 5s
      timeout: 5s
      retries: 12

networks:
  internal:

volumes:
  conductor_mysql:
